name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build & push image
      - name: Build, tag, push Docker image
        run: |
          IMAGE_TAG=latest
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # 5. Update kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name post-onboarding-eks

      # 6. Deploy MySQL (your mysql-deployment.yaml)
      - name: Apply MySQL Deployment
        run: |
          kubectl apply -f mysql-deployment.yaml

      # 7. Deploy your app
      - name: Deploy App to EKS
        run: |
          kubectl set image deployment/post-onboarding-deployment post-onboarding=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:latest
          kubectl rollout status deployment/post-onboarding-deployment
